application: hstspreload
version: 9
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
- url: /style.css
  script: _go_app
- url: /submit/.*
  script: _go_app
- url: /clear/.*
  script: _go_app
- url: /pending
  script: _go_app
- url: /update
  script: _go_app
- url: /robots.txt
  script: _go_app
- url: /favicon.ico
  script: _go_app
- url: /setmessage
  script: _go_app
- url: /setmessages
  script: _go_app
